name: Go Checks

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  native:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: fmt-check
        run: make fmt-check

      - name: tidy-check
        run: make tidy-check

      - name: lint-native
        run: make lint-native

      - name: native-check
        run: make native-check
